### ISSUE TITLE
How to generate the RicohCalib.mat file

### ISSUE THREAD

**Issue by fjordyo0707** [SunghoonIm/ADfSM#1]
Hi,
thanks for the awesome code. I really appreciate it.
However, I would like to use my own data on theta ricoh V.
And, I am wondering how can I get the file like RicohCalib.mat, or what is the calibration tool you are using to generate RicohCalib.mat.
Thank you.

**Comment by sunghoonim** [comment]
Hi,
I refer the several papers and toolbox for the camera calibration. 

For the intrinsic calibration (KL, KR, xiL, xiR), I used the following toolbox and paper:
http://www.robots.ox.ac.uk/~cmei/Toolbox.html#calib_params
http://www.robots.ox.ac.uk/~cmei/articles/single_viewpoint_calib_mei_07.pdf

For the extrinsic calibration (RT), I refer the paper:
https://pdfs.semanticscholar.org/e5f4/dfdb64adc3e625781d9908b7fa72ff3fb20b.pdf

**Comment by fjordyo0707** [comment]
Thanks for the quick reply and the share.
Really appreciate it !!
